import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#2A2539",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
    backgroundColor: "#BDD3CC",
  },
  backButton: {
    marginRight: 15,
    fontSize: 24,
    color: "#333",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginLeft: -10,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#2A2A2A",
  },
  moodTypeSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#262626",
    padding: 10,
    borderRadius: 20,
  },
  moodTypeText: {
    color: "white",
    fontSize: 16,
    marginRight: 5,
    textAlign: "center",
    marginTop: 5,
  },
  moodCountText: {
    color: "#00BFA5",
    fontSize: 16,
    marginRight: 5,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#262626",
    padding: 10,
    borderRadius: 20,
  },
  addButtonText: {
    color: "white",
    fontSize: 16,
    marginRight: 5,
  },
  scrollContent: {
    padding: 15,
    paddingBottom: 85,
  },
  calendarContainer: {
    backgroundColor: "#262626",
    borderRadius: 20,
    padding: 15,
    marginVertical: 10,
    borderWidth: 1.8,
    borderColor: "white",
  },
  calendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  monthText: {
    color: "white",
    fontSize: 22,
    fontWeight: "bold",
  },
  weekdaysContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 10,
  },
  weekdayText: {
    color: "#FFF",
    fontSize: 16,
    width: 40,
    textAlign: "center",
  },
  weekRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 15,
  },
  dayCell: {
    width: 40,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  dayCellContent: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  dayText: {
    color: "white",
    fontSize: 16,
    marginBottom: 3,
  },
  nonCurrentMonthDay: {
    opacity: 0.5,
  },
  nonCurrentMonthDayText: {
    color: "#BDDBCC",
  },
  selectedDayText: {
    color: "#BDDBCC",
    fontWeight: "bold",
  },
  todayDay: {
    borderWidth: 1,
    borderColor: "#BDDBCC",
  },
  todayText: {
    color: "#BDDBCC",
    fontWeight: "bold",
  },
  moodContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
  },
  multiMoodContainer: {
    flexDirection: "row",
    justifyContent: "center",
  },
  moodEmoji: {
    fontSize: 18,
  },
  moodColorIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 1,
  },
  moodCountBadge: {
    backgroundColor: "#00BFA5",
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 1,
    marginLeft: 2,
  },
  moodCountBadgeText: {
    color: "black",
    fontSize: 10,
  },
  addMoodButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#313131",
    justifyContent: "center",
    alignItems: "center",
  },
  // Tab bar styles
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#BDD3CC",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  tabText: {
    color: "balck",
    fontSize: 12,
    marginTop: 4,
  },
  addEntryButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#EDEFC8",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -40,
    borderWidth: 4,
    borderColor: "#000",
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#1E1E1E",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
  },
  closeModalButton: {
    padding: 5,
  },
  moodListScrollView: {
    maxHeight: 400,
  },
  moodListItem: {
    backgroundColor: "#262626",
    borderRadius: 15,
    marginBottom: 10,
    overflow: "hidden",
  },
  moodListItemContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
  },
  moodColorCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  moodListEmoji: {
    fontSize: 24,
  },
  moodTextContent: {
    flex: 1,
  },
  moodListName: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 3,
  },
  moodListTime: {
    color: "#7F7F7F",
    fontSize: 14,
  },
  moodNote: {
    color: "#BBBBBB",
    fontSize: 14,
    marginTop: 5,
  },
  addMoodListButton: {
    backgroundColor: "#BDDBCC",
    borderRadius: 30,
    padding: 15,
    marginTop: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  addMoodListButtonText: {
    color: "black",
    fontSize: 18,
    fontWeight: "bold",
  },

  gaugeChartContainer: {
    backgroundColor: "#262626",
    borderRadius: 20,
    padding: 20,
    marginTop: 20,
    marginBottom: 20,
    borderWidth: 1.8,
    borderColor: "white",
  },
  gaugeContainer: {
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  moodCountTitle: {
    color: "white",
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 5,
  },
  moodCountSubtitle: {
    color: "#7F7F7F",
    fontSize: 14,
    marginBottom: 10,
  },
  moodEmojiContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    paddingHorizontal: 5,
  },
  moodEmojiItem: {
    alignItems: "center",
    width: "18%",
  },
  emojiCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  emoji: {
    fontSize: 24,
  },
  emojiCountBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "white",
    width: 22,
    height: 22,
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#262626",
  },
  emojiCountText: {
    color: "black",
    fontSize: 12,
    fontWeight: "bold",
  },
  moodTypeText: {
    color: "white",
    fontSize: 12,
    marginTop: 8,
    textAlign: "center",
  },
});

export default styles;
