import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#BDD3CC",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#222",
  },
  monthNav: {
    flexDirection: "row",
    alignItems: "center",
  },
  navButton: {
    padding: 6,
    marginHorizontal: 25,
    borderRadius: 8,
  },
  monthTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000",
    marginHorizontal: 10,
  },
  searchButton: {
    padding: 8,
    fontWeight: "bold",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111",
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#333",
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    height: 40,
    color: "#fff",
    fontSize: 16,
  },
  clearButton: {
    padding: 5,
  },
  journalList: {
    paddingHorizontal: 16,
    paddingBottom: 100,
  },
  journalGroup: {
    marginBottom: 24,
  },
  dateHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  todayIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "black",
    marginRight: 10,
    marginTop: 15,
  },
  dateHeaderText: {
    color: "black",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 15,
  },
  journalEntryContainer: {
    position: "relative",
    marginBottom: 16,
  },

  journalCard: {
    backgroundColor: "#2A2539",
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  journalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  journalMoodContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  journalEmoji: {
    fontSize: 22,
  },
  journalInfo: {
    flex: 1,
  },
  journalMood: {
    fontSize: 16,
    fontWeight: "600",
  },
  journalMenuButton: {
    padding: 8,
  },
  journalActivities: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  journalActivity: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 16,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  journalActivityText: {
    color: "#fff",
    fontSize: 12,
    marginLeft: 4,
  },
  journalNote: {
    color: "#ddd",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  journalMedia: {
    marginTop: 8,
  },
  journalAudio: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: 15,
    padding: 12,
    marginBottom: 12,
  },
  audioProgressBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  audioDot: {
    width: 3,
    height: 20,
    borderRadius: 2,
    backgroundColor: "#EDEFC8",
    opacity: 0.6,
  },
  audioControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  audioDuration: {
    color: "#EDEFC8",
    fontSize: 12,
  },
  audioPlayButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#EDEFC8",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
  },
  imageGallery: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  journalImage: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 8,
    marginBottom: 8,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 8,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 16,
    color: "#aaa",
    marginBottom: 24,
    textAlign: "center",
  },
  noResultsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  noResultsText: {
    fontSize: 18,
    fontWeight: "500",
    color: "#ddd",
    marginTop: 16,
  },
  noResultsSubtext: {
    fontSize: 14,
    color: "#888",
    marginTop: 8,
  },
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#BDD3CC",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: "#222",
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navText: {
    color: "balck",
    fontSize: 12,
    marginTop: 4,
  },
  addButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#EDEFC8",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -30,
    borderWidth: 4,
    borderColor: "#000",
  },
  dropdownOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  dropdownContainer: {
    width: "80%",
    backgroundColor: "#2A2539",
    borderRadius: 12,
    overflow: "hidden",
  },
  dropdownOption: {
    paddingVertical: 16,
    paddingHorizontal: 24,
  },
  dropdownText: {
    color: "#fff",
    fontSize: 16,
  },
  deleteText: {
    color: "#ff4d4d",
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: "#333",
    marginVertical: 4,
  },
  moodSelectionOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  moodSelectionContainer: {
    width: "90%",
    backgroundColor: "#222",
    borderRadius: 16,
    padding: 24,
  },
  moodSelectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 24,
    textAlign: "center",
  },
  moodOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  moodOption: {
    width: "18%",
    aspectRatio: 1,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  moodEmoji: {
    fontSize: 28,
    marginBottom: 4,
  },
  moodLabel: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "500",
  },
  imageGallery: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  journalImage: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginBottom: 5,
  },
});

export default styles;
