import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#BDD3CC",
  },
  closeButton: {
    position: "absolute",
    top: 20,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.8,
    borderColor: "#333",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  closeButtonText: {
    color: "black",
    fontSize: 18,
    fontWeight: "bold",
  },
  contentContainer: {
    flex: 1,
    alignItems: "center",
    paddingTop: 100,
    paddingHorizontal: 20,
  },
  headerText: {
    color: "black",
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 60,
  },
  dateTimeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 60,
  },
  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "black", // Teal color for the underline
    paddingBottom: 5,
  },
  calendarIcon: {
    color: "black",
    marginRight: 5,
    fontSize: 16,
  },
  dateText: {
    color: "black",
    fontSize: 16,
  },
  dropdownIcon: {
    color: "black",
    fontSize: 12,
    marginLeft: 5,
  },
  timeSelector: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "black", // Teal color for the underline
    paddingBottom: 5,
  },
  clockIcon: {
    color: "#1ABC9C",
    marginRight: 5,
    fontSize: 16,
  },
  timeText: {
    color: "black",
    fontSize: 16,
  },
  moodContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 40,
  },
  moodItemContainer: {
    alignItems: "center",
  },
  moodCircle: {
    width: 55,
    height: 55,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: "black",
    borderRadius: 30,
  },
  moodEmoji: {
    fontSize: 21,
  },
  moodName: {
    color: "black",
    fontSize: 14,
    fontWeight: "bold",
  },
  selectMoodButton: {
    backgroundColor: "#EAE9E5",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    marginTop: 20,
    borderWidth: 1.5,
    borderColor: "#333",
  },
  selectMoodText: {
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
  },
  editMoodsButton: {
    position: "absolute",
    bottom: 80,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  editIcon: {
    fontSize: 20,
    marginRight: 5,
    borderWidth: 1.5,
    borderColor: "#333",
    backgroundColor: "rgba(223, 221, 221, 0.9)",
    padding: 10,
    borderRadius: 30,
    shadowColor: "#2A2539",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  editMoodsText: {
    color: "black",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 5,
    shadowColor: "#2A2539",
    shadowOpacity: 0.3,
    elevation: 4,
  },

  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  calendarContainer: {
    width: "96%",
    backgroundColor: "#EAE9E5",
    borderRadius: 20,
    borderWidth: 1.8,
    borderColor: "#333",
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  closeModalButton: {
    marginTop: 20,
    paddingVertical: 12,
    borderRadius: 25,
    width: "40%",
    marginLeft: "55%",
    marginBottom: 15,
    borderWidth: 1.5,
    borderColor: "#333",
    backgroundColor: "#EFC8C8",
    alignItems: "center",
  },
  closeModalText: {
    fontSize: 16,
    color: "black",
    fontWeight: "700",
  },
  selectedMoodCircle: {
    borderWidth: 3,
    borderColor: "White",
    transform: [{ scale: 1.1 }],
  },
  moodSelectedButton: {
    backgroundColor: "White",
  },
});

export default styles;
